### ISSUE TITLE
Multiple database support

### ISSUE THREAD

**Issue by nikolai-b** [Purple-Devs/health_check#100]
Related to #94 Rails 6 has multiple database connections.

Do you plan on adding support for checking the health of multiple databases, very crudely:

```ruby
ActiveRecord::Base.configurations.configs_for.select { |con| con.env_name == Rails.env }
```

?

**Comment by shlima** [comment]
@nikolai-b you can check an [alternative](https://github.com/shlima/health_bit)

**Comment by ianheggie** [comment]
At this point, No, I am not intending to code for multiple database support, but am happy to accept a PR if you want to code it.

If you send me a PR, or a custom health check, I can look at including it.
