### ISSUE TITLE
config.rabbitmq_config format more details

### ISSUE THREAD

**Issue by trombini77** [Purple-Devs/health_check#126]
About the Rabbitmq setup variable the only way that I did it work was using amqp URI format:

config.rabbitmq_config = "amqp://user:password@host:port/vhost"

Is there another format way to use it?

Please if there is would it be possible to add it to README?

Thanks.

**Comment by jmarchello** [comment]
Hi @trombini77. Thank you for your question and suggestion. I'll be able to look into this eventually, but in meantime I'd recommend you have a look in the code, and if you find something we'd love if you could submit a PR to update the documentation.

**Comment by jmarchello** [comment]
@trombini77 health_check uses the [Bunny gem](https://github.com/ruby-amqp/bunny) to interface with RabbitMQ. Whatever you define in `rabbitmq_config` is passed directly to `Bunny.new`. So I'd recommend looking at Bunny's docs to see what is supported there.
