### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by haffla** [Purple-Devs/health_check#127]
Hello @ianheggie,

is this project still maintained? It seems that development has come to a halt. Are you maybe looking for maintainers that could take over? The project urgently needs some updates. For example the Redis check doesn't work with redis-client, the new  standard Redis client in Sidekiq 7. There are many open PRs that look like they could be merged.

The project seems to be the [only popular](https://rubygems.org/search?query=health+check) health check gem for Rails applications and is used by many people/organizations.

**Comment by jmarchello** [comment]
Hello @haffla. Yes the project is still being maintained. I've just joined the project and will be assisting @ianheggie in supporting health_checks's continued development.

Stay tuned while I get ramped up and start working through our backlog of issues and Pull Requests.

**Comment by jmarchello** [comment]
@haffla Would you open a separate issue regarding redis-client support with a little more detail? This will allow us to properly address and track that request. Thanks!

**Comment by haffla** [comment]
Cool @jmarchello. I am happy to hear that this project gets some love. I am going to open an issue regarding Redis.
